### ISSUE TITLE
Open mkxp-z console

### ISSUE THREAD

**Issue by Nathan-MV** [SnowSzn/rgss-script-editor#1]
As it is, it's not opening the console

**Comment by SnowSzn** [comment]
Hi,

I have tested mkxp-z for Windows with a test project in RPG Maker VX Ace and RPG Maker XP and it shows me the console window without problems.

What operating system are you using this extension on?

**Comment by Nathan-MV** [comment]
Ah, my mistake, i was testing with the fix (that is not yet merged) for using the default terminal in Windows so it was not opening the console
